#28 user menagement pipeline behaviour validation + logging
InFiNet-Code-AB/Dojo-BE pull request #109
Opened 2024-04-01 22:59 UTC by BojanMirkovic

#28 user menagement pipeline behaviour validation + logging

## Description
I have created Pipeline Behaviour for User Pipeline. It consist from two generic classes, ValidationBehaviour and LoggingBehaviour. I was following CQRS and I have created Validators/Validation Extensions with validation rules and I have implement these validation Extensions in Command/Query Validators making sure that I am following DRY principal.

## Changes Made

I have made small changes in Commands/Queries where I have removed unused using statements.

## Related Ticket or Issue

#91 

## Checklist

- [x] Code adheres to the coding conventions
- [] Unit tests are added for new code
- [] Existing unit tests are updated if needed
- [x] Code follows the principles of Clean Architecture
- [x] Code formatting complies with the `.editorconfig` file
- [x] Pull request template is filled out

2024-04-03 08:40 UTC, Nemanja1208 requested changes
Good work Bojan, small changes needed.

2024-04-03 08:40 UTC, Nemanja1208 commented on Application-Layer/PipelineBehaviour/ValidationBehaviour.cs
> +                /*dont forget to ctatch ValidationException in GlobalException Handler and
Delete comment

2024-04-03 08:40 UTC, Nemanja1208 commented on Application-Layer/PipelineBehaviour/LoggingBehaviour.cs
> +                object propValue = prop.GetValue(request, null)!;
Question here > Do we want to log everything ? If we do this with each request it can slow down our app a lot...
But we can keep it for now just for development puproses, I just wanted to highlight that later, we will probably want to remove this and log only important stuff...

```csharp
  var propValue = prop.GetValue(request);
  if (propValue != null)
  {
      _logger.LogInformation("{Property} : {@Value}", prop.Name, propValue);
  }
```
Maybe it will be null sometime...

2024-04-03 09:13 UTC, BojanMirkovic commented on Application-Layer/PipelineBehaviour/LoggingBehaviour.cs
> +                object propValue = prop.GetValue(request, null)!;
logging part is not completely clear to me, even that I know that this is the way to truck the code behaviour, and that we are using logging to document and display errors in debugging process I still don’t know how to use it and how to determine what is important and what is not. It would be great if you can explain this topic to me .

2024-04-04 22:23 UTC, ElliotDahlin approved these changes
well done !

2024-04-05 06:07 UTC, Nemanja1208 requested changes
Change needed for registering the PipelineBehavior

2024-04-05 06:07 UTC, Nemanja1208 commented on Application-Layer/DependencyInjection.cs
> +            services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehaviour<,>));
Why both transient and scoped for this service ? It should be only 1

2024-04-05 08:06 UTC, BojanMirkovic commented on Application-Layer/DependencyInjection.cs
> +            services.AddTransient(typeof(IPipelineBehavior<,>), typeof(ValidationBehaviour<,>));
You are right, I didnt notice that when I have implement LoggingBehaviour I didnt delete Transient ValidationBehaviour lifetime which I used in first place.

2024-04-07 19:59 UTC, Nemanja1208 approved these changes

2024-04-07 19:59 UTC, merged