#28 user management update user command+handler branch update
InFiNet-Code-AB/Dojo-BE pull request #82
Opened 2024-03-15 21:14 UTC by BojanMirkovic

# #28 user management update user command+handler branch update

## Description
I have created UpdatingUserDTO, UpdateUserCommand + Handler .

## Changes Made
I have generate UpdateUserAsync() in IUserRepositoy + UserRepository
  

## Related Ticket or Issue
#45 #48 
## Checklist

- [x] Code adheres to the coding conventions
- [] Unit tests are added for new code
- [] Existing unit tests are updated if needed
- [x] Code follows the principles of Clean Architecture
- [x] Code formatting complies with the `.editorconfig` file
- [x] Pull request template is filled out

2024-03-15 22:09 UTC, Nemanja1208 requested changes
Look very good, just a little comment

2024-03-15 22:09 UTC, Nemanja1208 commented on Application-Layer/Commands/UpdateUser/UpdateUserCommand.cs
> +            Email = email;
Is it not easier to have the Email property as the part of DTO ?

2024-03-15 22:34 UTC, BojanMirkovic commented on Application-Layer/Commands/UpdateUser/UpdateUserCommand.cs
> +            Email = email;
I didn’t have planned to have option to update Email. Email was meant to be used instead of Username and it should be only one Email per Account/registration. But if you think that Email should be possible to update, I can change that be part of DTO. I was using Email just to find User to update.

2024-03-15 23:04 UTC, BojanMirkovic reviewed
I have changed the name of UpdateUserCommand proprty to avoid confusion to string UsersEmail. I need string property to pass value into GetUserByEmail(string) in my UpdateUserCommandHandler

2024-03-16 10:44 UTC, HubTicaBB commented on Application-Layer/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +                userToUpdate = _mapper.Map<UserModel>(request.UpdatingUserInfo);
Not required, it might work this way too as long as it's able to find matching properties, but it's a good practice to define mapping profiles explicitly, something like:

```csharp
public class MappingProfiles : Profile
{
    public MappingProfiles()
    {
        CreateMap<UpdatingUserDTO, UserModel>();
        CreateMap<AnotherDto, AnotherModel>();
        // etc.
    }
}
```

Then you can use it like `_mapper.Map(request.UpdatingUserInfo, userToUpdate);`

This way you keep control over mapping instead of risking missmatch.

2024-03-16 10:46 UTC, HubTicaBB commented on Application-Layer/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +                userToUpdate = _mapper.Map<UserModel>(request.UpdatingUserInfo);
I might be blind, but I don't see the `AutoMapper` in the services. Make sure to add `AddAutoMapper`. If you opt for using mapping profiles, than provide the profiles type to it.

2024-03-16 13:03 UTC, BojanMirkovic commented on Application-Layer/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +                userToUpdate = _mapper.Map<UserModel>(request.UpdatingUserInfo);
I did that way as you have suggested, services are located in Aplication-Layer DI, and MappingProfile is located in Aplication-Layer AutoMaper just under the name UserProfile. 
What I have forgot is to include CreateMap<UpdatingUserDTO, UserModel>();
And now I am going to change name of UserProfile to AutoMapper and I am going to change the way I implement mapper.

2024-03-16 14:01 UTC, BojanMirkovic commented on Application-Layer/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +                userToUpdate = _mapper.Map<UserModel>(request.UpdatingUserInfo);
I did small investigation about difference in this two implementation and you are right 100%, I was wrong I thought that they are doing same thing but they dont. 
I am changing line as you have suggested.

2024-03-16 14:06 UTC, BojanMirkovic reviewed
I made changes as it was suggested.

2024-03-16 15:47 UTC, Nemanja1208 requested changes
Check comment again

2024-03-16 15:47 UTC, Nemanja1208 commented on Application-Layer/Commands/UpdateUser/UpdateUserCommandHandler.cs
> +            var userToUpdate = await _userRepository.GetUserByEmailAsync(request.UsersEmail);
You already have email in the DTO as you say, so why have duplicates ? You can do like this
```cs
var userToUpdate = await _userRepository.GetUserByEmailAsync(request.UpdatingUserInfo.Email);
```

2024-03-16 17:33 UTC, BojanMirkovic reviewed
Email property is removed because we are using DTOs Email as it was advised.

2024-03-16 19:22 UTC, Nemanja1208 approved these changes
Good work

2024-03-16 19:47 UTC, merged